-- Demo invite tokens — generated by admin, claimed once by a prospect
CREATE TABLE IF NOT EXISTS demo_tokens (
  token        TEXT PRIMARY KEY,
  created_at   TEXT NOT NULL,
  expires_at   TEXT NOT NULL,
  claimed_at   TEXT,
  claimant_email TEXT
);
